apiVersion: v1
kind: Service
metadata:
  name: text-generation-service
spec:
  selector:
    app: text-generation
  ports:
    - protocol: TCP
      port: 7860    #80 default
      targetPort: 7860
  type: ClusterIP
