apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-generation-deployment
spec:
  selector:
    matchLabels:
      app: text-generation
  replicas: 1
  template:
    metadata:
      labels:
        app: text-generation
    spec:
      containers:
        - name: text-generation-container
          image: wiktoria02/text-generation:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 7860
          env:
            - name: LD_LIBRARY_PATH
              value: "/usr/local/cuda-12.6/compat"
            #- HF_TOKEN PATH
          volumeMounts:
            - mountPath: "/home/app/text-generation-webui/models"
              name: textgen-storage-1
            - mountPath: "/home/app/text-generation-webui/training/datasets"
              name: textgen-storage-2
      volumes:
        - name: textgen-storage-1
          persistentVolumeClaim:
            claimName: text-generation-webui-pvc1
        - name: textgen-storage-2
          persistentVolumeClaim:
            claimName: text-generation-webui-pvc2
