apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-generation-deployment
spec:
  selector:
    matchLabels:
      app: text-generation
  replicas: 1
  template:
    metadata:
      labels:
        app: text-generation
    spec:
      containers:
        - name: text-generation-container
          image: wiktoria02/text-generation:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 7860
          env:
            - name: LD_LIBRARY_PATH
              value: "/usr/local/cuda-12.6/compat"
      #     volumeMounts:
      #       - mountPath: "/home/app/text-generation-webui/models"
      #         name: textgen-storage
      #       - mountPath: "/home/app/text-generation-webui/training/datasets"
      #         name: textgen-storage
      # volumes:
      #   - name: textgen-storage
      #     persistentVolumeClaim:
      #       claimName: text-generation-webui-pvc
