apiVersion: v1
kind: PersistentVolume
metadata:
  name: text-generation-webui-pv
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"