apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: text-generation-webui-pvc2
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi