apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: text-generation-webui-pvc1
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi