apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: text-generation-dockerhub-sensor
  namespace: argo
spec:
  template:
    serviceAccountName: argo     # service account created at installation of argo events
    containers:
      - name: sensor
        # args:
        #   - --port=12000
        ports:
          - containerPort: 12000
  dependencies:
    - name: dockerhub
      eventSourceName: webhook
      eventName: dockerhub
  triggers:
    - template:
        name: trigger-rollout-workflow
        argoWorkflow:
          group: argoproj.io
          version: v1alpha1
          resource: Workflow
          operation: submit
          source:
            workflowRef:
              name: workflow-pull-image           #pipeline resposible for doing rollout
              namespace: argo
          # parameters:
          #   - src:
          #       dependencyName: dockerhub
          #       dataKey: repository.repo_name
          #     dest: spec.arguments.parameters.0.value
          #   - src:
          #       dependencyName: dockerhub
          #       dataKey: push_data.tag
          #     dest: spec.arguments.parameters.1.value
      #condition: "{{ .inputs.dockerhub.push_data.tag == 'latest' }}"       #workflow starts if push event is detected /webhook
      #if payloads push_data and push_data.tag aren't null, the rollout will happen