apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
  namespace: argo-events
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: dependon-eventsource
      eventSourceName: webhook
      eventName: dockerhub
  triggers:
    - template:
        name: webhook-workflow-trigger
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: pull-docker-image-
                labels:
                  workflows.argoproj.io/archive-strategy: "false"
                annotations:
                  workflows.argoproj.io/description: |
                    This pipeline does a deployment rollout to replace pods to ones with newer image.
              spec:
                workflowTemplateRef:
                  name: deployment-update-workflow
                  namespace: argo-events
                arguments:
                  parameters:
                  - name: image-tag
                    value: "{{events.trigger.event.body.push_data.tag}}"
          parameters:
            - src:
                dependencyName: dependon-eventsource
              dest: spec.arguments.parameters.0.value  # map event data to workflow parameter
    # - template:
    #     name: downloading-llm
    #     k8s:
    #       operation: create
    #       source:
    #         resource:
    #           apiVersion: argoproj.io/v1alpha1
    #           kind: Workflow
    #           metadata:
    #             generateName: download-llm-from-hugging-face-
    #             labels:
    #               workflows.argoproj.io/archive-strategy: "false"
    #             annotations:
    #               workflows.argoproj.io/description: |
    #                 This pipeline downloads llm form The Hugging Face repository.
    #           spec:
    #             workflowTemplateRef:
    #               name: download-and-apply-llm
    #               namespace: argo-events
