apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: dependon-eventsource
      eventSourceName: webhook
      eventName: dockerhub
  triggers:
    - template:
        name: webhook-workflow-trigger
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: hello-world-
                labels:
                  workflows.argoproj.io/archive-strategy: "false"
                annotations:
                  workflows.argoproj.io/description: |
                    This is a simple hello world example.
              spec:
                entrypoint: hello-world
                templates:
                - name: hello-world
                  container:
                    image: busybox
                    command: [echo]
                    args: ["hello world"]