apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: webhook-
  namespace: argo  # Określamy namespace "argo"
spec:
  entrypoint: whalesay
  arguments:
    parameters:
      - name: message
        value: hello world
  templates:
    - name: whalesay
      inputs:
        parameters:
          - name: message
      container:
        image: docker/whalesay:latest
        command: [cowsay]
        args: ["{{inputs.parameters.message}}"]
