apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rollout-restart-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["deployments"]
    verbs: ["get", "list", "update", "patch", "create"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "update", "patch", "create"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rollout-restart-role-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: default
    namespace: argo-events 
roleRef:
  kind: Role
  name: rollout-restart-role
  apiGroup: rbac.authorization.k8s.io
