apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook
  namespace: argo
spec:
  eventBusName: default
  service:
    ports:
      - port: 12000
        targetPort: 12000
  webhook:
    dockerhub:
      endpoint: /dockerhub
      method: POST
      port: "12000"
      host: "0.0.0.0"